export const SentAILogger = [
	{
		inputs: [{ name: "forwarder", type: "address" }],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{
		inputs: [],
		name: "decisionCount",
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ name: "", type: "uint256" }],
		name: "decisions",
		outputs: [
			{ name: "timestamp", type: "uint256" },
			{ name: "sentimentScore", type: "uint8" },
			{ name: "confidence", type: "uint8" },
			{ name: "action", type: "string" },
			{ name: "marketSlug", type: "string" },
			{ name: "sizeUsdc", type: "uint256" },
			{ name: "suggestedPrice", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ name: "id", type: "uint256" }],
		name: "getDecision",
		outputs: [
			{
				name: "",
				type: "tuple",
				components: [
					{ name: "timestamp", type: "uint256" },
					{ name: "sentimentScore", type: "uint8" },
					{ name: "confidence", type: "uint8" },
					{ name: "action", type: "string" },
					{ name: "marketSlug", type: "string" },
					{ name: "sizeUsdc", type: "uint256" },
					{ name: "suggestedPrice", type: "uint256" },
				],
			},
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ name: "slug", type: "string" }],
		name: "getDecisionsBySlug",
		outputs: [{ name: "", type: "uint256[]" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ name: "", type: "bytes32" },
			{ name: "", type: "uint256" },
		],
		name: "decisionsBySlug",
		outputs: [{ name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ name: "", type: "bytes32" }],
		name: "processedReports",
		outputs: [{ name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ name: "metadata", type: "bytes" },
			{ name: "report", type: "bytes" },
		],
		name: "onReport",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ name: "interfaceId", type: "bytes4" }],
		name: "supportsInterface",
		outputs: [{ name: "", type: "bool" }],
		stateMutability: "pure",
		type: "function",
	},
	{
		inputs: [
			{ name: "id", type: "uint256", indexed: true },
			{ name: "timestamp", type: "uint256", indexed: true },
			{ name: "sentimentScore", type: "uint8", indexed: false },
			{ name: "confidence", type: "uint8", indexed: false },
			{ name: "action", type: "string", indexed: false },
			{ name: "marketSlug", type: "string", indexed: false },
			{ name: "sizeUsdc", type: "uint256", indexed: false },
			{ name: "suggestedPrice", type: "uint256", indexed: false },
		],
		name: "SentAIDecision",
		anonymous: false,
		type: "event",
	},
] as const;
